export const retroModernTokens = {
  colors: {
    desktopBg: "#0a0e14",
    desktopGrid: "rgba(212, 167, 106, 0.06)",
    surface: "#1a212b",
    surfaceElevated: "#222a36",
    surfaceLight: "#333e4f",
    surfaceDark: "#0d1218",
    titlebarActiveStart: "#142236",
    titlebarActiveEnd: "#23395b",
    titlebarInactiveStart: "#14181f",
    titlebarInactiveEnd: "#1c222b",
    titlebarText: "#ffffff",
    goldAccent: "#d4a76a",
    goldMuted: "rgba(212, 167, 106, 0.2)",
    emerald: "#5bd3a1",
    coral: "#ff6b6b",
    textPrimary: "#f5f5f5",
    textMuted: "#a0aec0",
  },
  typography: {
    systemFont: "'MS Sans Serif', 'Segoe UI', Tahoma, sans-serif",
    monospace: "'Courier New', monospace",
  },
  zIndex: {
    canvas: 1,
    gadget: 20,
    windowBase: 50,
    startMenu: 900,
    taskbar: 1000,
    modal: 2000,
  },
} as const;

export const appMetadataList = [
  {
    id: "about",
    title: "About Raihan - Personal Dossier",
    iconLabel: "About",
    filename: "ABOUT.EXE",
    defaultSize: { width: 560, height: 430 },
    defaultPosition: { x: 50, y: 35 },
  },
  {
    id: "projects",
    title: "Selected Projects - File Explorer",
    iconLabel: "Projects",
    filename: "PROJECTS.DIR",
    defaultSize: { width: 700, height: 470 },
    defaultPosition: { x: 110, y: 65 },
  },
  {
    id: "skills",
    title: "System Properties - Tech Stack",
    iconLabel: "Skills",
    filename: "SKILLS.SYS",
    defaultSize: { width: 520, height: 410 },
    defaultPosition: { x: 170, y: 95 },
  },
  {
    id: "contact",
    title: "Compose Message - Outlook Express",
    iconLabel: "Contact",
    filename: "CONTACT.MSG",
    defaultSize: { width: 520, height: 440 },
    defaultPosition: { x: 210, y: 125 },
  },
  {
    id: "easteregg",
    title: "not-a-virus.docx - WordPad",
    iconLabel: "WordPad",
    filename: "NOT-A-VIRUS.DOCX",
    defaultSize: { width: 480, height: 360 },
    defaultPosition: { x: 250, y: 155 },
  },
] as const;
